
import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const getMimeType = (base64: string): string | null => {
    const match = base64.match(/^data:(image\/[a-z]+);base64,/);
    return match ? match[1] : null;
}

const cleanBase64 = (base64: string): string => {
    return base64.replace(/^data:image\/[a-z]+;base64,/, '');
}

export const generateNailArtImage = async (
  destinationImageBase64: string,
  sourceImageBase64: string
): Promise<string> => {
    const model = 'gemini-2.5-flash-image';
    
    const destinationMimeType = getMimeType(destinationImageBase64);
    const sourceMimeType = getMimeType(sourceImageBase64);
    
    if (!destinationMimeType || !sourceMimeType) {
        throw new Error("Could not determine image MIME type from base64 string.");
    }
    
    const prompt = `Analyze the nail art design from the second image (the source). Apply this exact nail art design to the nails of the hand in the first image (the destination). The final generated image should be a realistic photo of the hand from the first image but with the new nail design perfectly applied. Do not change the hand shape, skin tone, or background of the first image. Only modify the nails.`;

    const response = await ai.models.generateContent({
        model: model,
        contents: {
          parts: [
            {
              inlineData: {
                data: cleanBase64(destinationImageBase64),
                mimeType: destinationMimeType,
              },
            },
            {
              inlineData: {
                data: cleanBase64(sourceImageBase64),
                mimeType: sourceMimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
        config: {
          responseModalities: [Modality.IMAGE],
        },
    });
    
    const firstPart = response?.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && 'inlineData' in firstPart && firstPart.inlineData) {
        const generatedImageData = firstPart.inlineData;
        return `data:${generatedImageData.mimeType};base64,${generatedImageData.data}`;
    }

    throw new Error('No image was generated by the API.');
};
